# Generated by Django 5.2.3 on 2025-06-15 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CategoryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Model', 'Tolerance Limit', 'Material of Construction'", max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Order in which this parameter appears in the table')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='main.category')),
            ],
            options={
                'verbose_name': 'Category Parameter',
                'verbose_name_plural': 'Category Parameters',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Value for this parameter (e.g., 'NC-5K-E1-ASS', '± 2.5 mg')", max_length=500)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoryparameter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='main.product')),
            ],
            options={
                'verbose_name': 'Product Parameter Value',
                'verbose_name_plural': 'Product Parameter Values',
                'unique_together': {('product', 'parameter')},
            },
        ),
    ]
