# Generated by Django 5.2.3 on 2025-06-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the document (e.g., 'Product Manual', 'Certificate of Calibration')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the document.', null=True)),
                ('file', models.FileField(help_text='Upload the document file (PDF, DOCX, etc.)', upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at', 'title'],
            },
        ),
    ]
