# Generated by Django 5.1 on 2025-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quotationrequest_quotationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company (for alt text)', max_length=255)),
                ('logo_image', models.ImageField(help_text='Upload the company logo image', upload_to='customer_logos/')),
                ('website_url', models.URLField(blank=True, help_text="Optional: URL to the customer's website", null=True)),
                ('order', models.IntegerField(default=0, help_text='Order for display, primarily for admin organization.')),
            ],
            options={
                'verbose_name': 'Customer Logo',
                'verbose_name_plural': 'Customer Logos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
