# Generated by Django 5.1 on 2025-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customerlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogo',
            name='logo_image',
            field=models.FileField(help_text='Upload the company logo image', upload_to='customer_logos/'),
        ),
    ]
